setup_pgsql:
	docker run \
	-d \
	-p 5432:5432 \
	--name postgresql \
	-e POSTGRESQL_USERNAME=postgres \
	-e POSTGRESQL_DATABASE=hot_desking \
	-e POSTGRESQL_PASSWORD=postgres \
	bitnami/postgresql:latest

